main/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('', views.home, name='accueil'),
    path('getlogin', views.getlogin),
    path('login', views.login_user),
    path('analyse_list/<str:user>/<int:patientPk>', views.analyse_list),
    path('new_analyse/<str:user>/<int:patientPk>', views.new_analyse),
    path('addImage/<int:analysePk>', views.addImage),
    path('make_analyse/<int:analysePk>', views.make_analyse),
    path('atest', views.atest),
    path('inference', views.inference),
]

malariawebapp/urls.py
from django.contrib import admin
from django.urls import include, path
from main import  urls
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
prefix_default_language=False
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone


class Hopital(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nom", unique=True )
    logo = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name="Logo du site")
    phone = models.IntegerField( help_text='Numéro de téléphone', verbose_name="Numéro de téléphone", unique=True)
    mail = models.EmailField(max_length=50, verbose_name="Adresse mail contact", unique=True)
    adresse = models.TextField(null=True, blank=True , default="#", verbose_name="Adresse")
   
    class Meta:
        verbose_name = "Hopital"
        #ordering = ['name']

    def __str__(self):
        return self.name

class Patient(models.Model):
    firstname = models.CharField(max_length=100, verbose_name="Prénoms")
    lastname = models.CharField( max_length=500, verbose_name="Nom")
    phone1 = models.IntegerField( help_text='Numéro de téléphone', verbose_name="Numéro de téléphone", unique=True)
    mail = models.EmailField(max_length=50, verbose_name="Adresse mail", unique=True)
    adresse = models.TextField(null=True, blank=True , default="#", verbose_name="Adresse")
    photo = models.ImageField(upload_to='images/',null=True, blank=True, verbose_name="Photo", default='images/photo.png')
   
    class Meta:
        verbose_name = "Patient"
        #ordering = ['name']

    def __str__(self):
        return self.firstname+' '+self.lastname


class Agent(models.Model):
    firstname = models.CharField(max_length=100, verbose_name="Prénoms")
    lastname = models.CharField( max_length=500, verbose_name="Nom")
    phone1 = models.IntegerField( help_text='Numéro de téléphone', verbose_name="Numéro de téléphone", unique=True)
    mail = models.EmailField(max_length=50, verbose_name="Adresse mail", unique=True)
    adresse = models.TextField(null=True, blank=True , default="#", verbose_name="Adresse")
    photo = models.ImageField(upload_to='images/',null=True, blank=True, verbose_name="Photo")
    hopital = models.OneToOneField(Hopital, null=True, on_delete = models.PROTECT)
   
    class Meta:
        verbose_name = "Agent médical"

    def __str__(self):
        return self.firstname+' '+self.lastname



class Analyse(models.Model):
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    patient = models.ForeignKey(Patient, null=True, on_delete = models.PROTECT)
    infected_cells = models.IntegerField(verbose_name="Nombre de cellules infectées",null=True, blank=True  )
    #infected_cells = models.IntegerField(max_length=100, verbose_name="Nombre de cellules infectées" )
    class Meta:
        verbose_name = "Analyse"
        #ordering = ['name']

    def __str__(self):
    	return self.patient.firstname+ ',  '+ self.patient.lastname+ ',  '+ str(self.created_at)



class Image(models.Model):
    file = models.ImageField(upload_to='media/analyse/', verbose_name="Champs de vision")
    analyse = models.ForeignKey(Analyse, null=True,  on_delete = models.CASCADE)
    class Meta:
        verbose_name = "Champs de vision"
        #ordering = ['name']

    def __str__(self):
    	return self.file.path

templates/analyse.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Malaria diagnosis Project</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}"  rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}"  rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700' %}"  rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/magnific-popup/magnific-popup.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}"  rel="stylesheet">

  <!-- =======================================================
    Theme Name: Reveal
    Theme URL: https://bootstrapmade.com/reveal-bootstrap-corporate-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="body">


  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container">

      <div id="logo" class="pull-left" style=" margin-bottom: 0; padding-bottom: 0">
        <h1 style="font-size: 1.7em;"><a href="/"  class="scrollto">Pred<span>Malaria</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% static '#body' %}" ><img src="{% static 'img/logo.png' %}"  alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="/" >Accueil</a></li>
          <li><a href="#about" >{{user}}</a></li>
          <li><a href="#contact" >Déconnexion</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

  
    <!--==========================
      Services Section
    ============================-->
    <section id="services">
      <div class="container">
        <div class="section-header">
          <h2>Nouvelle analyse </h2>
          <p>Patient: {{patient}}</p>
        </div>
        <div class="row ">
            <div class=" col-md-8 wow fadeInRight" style="visibility: visible; animation-name: fadeInRight;">
              <h4 class="title" style=" margin-left: 0">Vision</h4>
                <div class="video-wrap">
                    <video id="video" playsinline autoplay></video>
                </div>
                <span id="errorMsg"></span>
                <canvas id="canvas" width="640" height="480" style="display: none"></canvas>
            </div>
            <div class="col-md-4"  style="visibility: visible; animation-name: fadeInRight;">
              <h4 class="title"  style=" margin-left: 0">Champs de vision</h4>
              <div class="controller" >
                    <button class="btn btn-primary" id="snap">Capturer</button>  
                    <button class="btn btn-outline-info" onclick="upload()" id="analyse">Analyser</button>
                </div>
              <div class="row" id="champsDeVision" style="margin-top: 15px"></div>
            </div>
            <img src="" id="imageView" style="display: none">
          </div>
      </div>
    </section><!-- #services -->

  

  </main>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer" style="margin-top: 22% ">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Reveal</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Reveal
        -->
        Designed by <a href="{% static 'https://bootstrapmade.com/' %}" >BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#"  class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}" ></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}" ></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}" ></script>
  <script src="{% static 'lib/easing/easing.min.js' %}" ></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}" ></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}" ></script>
  <script src="{% static 'lib/wow/wow.min.js' %}" ></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}" ></script>
  <script src="{% static 'lib/magnific-popup/magnific-popup.min.js' %}" ></script>
  <script src="{% static 'lib/sticky/sticky.js' %}" ></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}" ></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}" ></script>
  <script type="text/javascript">
    /*
    <input type="file" accept="image/*" capture>
    <input type="file" accept="image/*" capture="user">
    <input type="file" accept="image/*" capture="environment">*/
    $('#id_file').replaceWith('<input id="id_file" type="file" accept="image/*" capture="camera">')
  </script>
  <script type="text/javascript">
    'use strict';

    const video = document.getElementById('video');
    const canvas = document.getElementById('canvas');
    const snap = document.getElementById("snap");

    const constraints = {
      audio: true,
      video: {
        width: 480, height: 320
      }
    };

    // Access webcam
    async function init() {
      console.log('init')
      try {
        const stream = await navigator.mediaDevices.getUserMedia(constraints);
        handleSuccess(stream);
      } catch(e) {
        console.log('error'+', '+e)
        //$('span#errorMsg').text(navigator.getUserMedia+', '+e )
        //errorMsgElement.innerHTML = 'navigator.getUserMedia error:${e.toString()}';
      }
    }

    // Success
    function handleSuccess(stream) {
      console.log('handleSuccess')
      window.stream = stream;
      video.srcObject = stream;
    }

    // Load init
    init();

    var context = canvas.getContext('2d');
    $('#snap').click(function() {
      //$(this).html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>Capture...').attr('disabled', true)
      context.drawImage(video, 0, 0, 480, 320);
      var image = new Image();
      image.id = "pic";
      image.src = canvas.toDataURL();
      //image.wrap('<div class="col-md-6" ></div>')
      $('#champsDeVision').append(image)
      $('#pic').wrap('<div class="col-12" style="margin:0; padding:0; height: 340px" ></div>').attr('id','').css('padding','0').css('margin','0').addClass('champ-vision').dblclick(function(){ $(this).remove()})

        fetch(image.src).then(res => res.blob()).then(blob => {
          var file = new File([blob], 'image.jpg', blob)
          console.log( 'before call api: ' +file.name)
          var form = new FormData();
          form.append("file", file);
          var settings = {
            "async": true,
            "crossDomain": true,
            "url": "/addImage/{{analyse.pk}}",
            "method": "POST",
            "processData": false,
            "contentType": false,
            "data": form
          }

          $.ajax(settings).done(function (response) {
            console.log('cool')
            console.log(response.message)
            //$('#snap').html('Capturer').attr('disabled', false)
          });
        })
      console.log('end')
    });
  </script>
<script >

  function upload(){
    console.log('upload')
 
	  var request = $.ajax({
                    url: "/make_analyse/{{analyse.pk}}",
                    method: "POST",
                    headers: {'X-CSRFToken': '{{ csrf_token }}'},
                    });	
          request.done(function (response) {
            //console.log('cool')
            console.log(response.predictions)
          });
    /*$('.champ-vision').each(function(){
        //const image = $(this)
        $('#imageView').attr('src', $(this).attr('src') )
        const image = document.getElementById('imageView')
        var file= null
        fetch(image.src).then(res => res.blob()).then(blob => {
          file = new File([blob], 'image.jpg', blob)
          console.log( 'before call api: ' +file.name)
          var form = new FormData();
          form.append("file", file);
          var settings = {
            "async": true,
            "crossDomain": true,
            "url": "/addImage/{{analyse.pk}}",
            "method": "POST",
            "processData": false,
            "contentType": false,
            "data": form
          }

          $.ajax(settings).done(function (response) {
            console.log('cool')
            console.log(response.message)
          });
        })
    });
    console.log('end')*/
  }
  
</script> 
</body>
</html>

templates/analyse2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Malaria diagnosis Project</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}"  rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}"  rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700' %}"  rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/magnific-popup/magnific-popup.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}"  rel="stylesheet">

  <!-- =======================================================
    Theme Name: Reveal
    Theme URL: https://bootstrapmade.com/reveal-bootstrap-corporate-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="body">


  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container">

      <div id="logo" class="pull-left" style=" margin-bottom: 0; padding-bottom: 0">
        <h1 style="font-size: 1.7em;"><a href="/"  class="scrollto">Pred<span>Malaria</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% static '#body' %}" ><img src="{% static 'img/logo.png' %}"  alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="/" >Accueil</a></li>
          <li><a href="#about" >{{user}}</a></li>
          <li><a href="#contact" >Déconnexion</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

  
    <!--==========================
      Services Section
    ============================-->
    <section id="services">
      <div class="container">
        <div class="section-header">
          <h2>Nouvelle analyse </h2>
          <p>Patient: {{patient}}</p>
        </div>
        <div class="row ">
            <div class="col-md-3"></div>
            <div class="box wow fadeInRight" style="visibility: visible; animation-name: fadeInRight;">
              <div class="icon"><i class="fa fa-picture-o"></i></div>
              <h4 class="title">Ajouter un champ de vision</h4>
            
                <form id=""  >
                  {% csrf_token %}
                  {{ imageForm.as_p }}
                  <button type="submit"   class="btn  btn-primary" >Capturere</button>     
                </form>
                <!-- Stream video via webcam -->
                <video id="player" controls autoplay></video>
                <script>
                  const supported = 'mediaDevices' in navigator;
                  const player = document.getElementById('player');
                  const constraints = {
                    video: true,
                  };

                  navigator.mediaDevices.getUserMedia(constraints)
                    .then((stream) => {
                      player.srcObject = stream;
                    });
                </script>

             
            </div>
          </div>
      </div>
    </section><!-- #services -->

  

  </main>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer" style="margin-top: 22% ">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Reveal</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Reveal
        -->
        Designed by <a href="{% static 'https://bootstrapmade.com/' %}" >BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#"  class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}" ></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}" ></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}" ></script>
  <script src="{% static 'lib/easing/easing.min.js' %}" ></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}" ></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}" ></script>
  <script src="{% static 'lib/wow/wow.min.js' %}" ></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}" ></script>
  <script src="{% static 'lib/magnific-popup/magnific-popup.min.js' %}" ></script>
  <script src="{% static 'lib/sticky/sticky.js' %}" ></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}" ></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}" ></script>
  <script type="text/javascript">
    /*
    <input type="file" accept="image/*" capture>
    <input type="file" accept="image/*" capture="user">
    <input type="file" accept="image/*" capture="environment">*/
    $('#id_file').replaceWith('<input id="id_file" type="file" accept="image/*" capture="camera">')
  </script>

</body>
</html>

templates/analyses.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Malaria diagnosis Project</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}"  rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}"  rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700' %}"  rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/magnific-popup/magnific-popup.css' %}"  rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}"  rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}"  rel="stylesheet">

  <!-- =======================================================
    Theme Name: Reveal
    Theme URL: https://bootstrapmade.com/reveal-bootstrap-corporate-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="body">


  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container">

      <div id="logo" class="pull-left" style=" margin-bottom: 0; padding-bottom: 0">
        <h1 style="font-size: 1.7em;"><a href="/"  class="scrollto">Pred<span>Malaria</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% static '#body' %}" ><img src="{% static 'img/logo.png' %}"  alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="/" >Accueil</a></li>
          <li><a href="#about" >{{user}}</a></li>
          <li><a href="#contact" >Déconnexion</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

  
    <!--==========================
      Services Section
    ============================-->
    <section id="services">
      <div class="container">
        <div class="section-header">
          <h2>Analyses &nbsp&nbsp<a href="/new_analyse/{{user}}/{{patientPk}}" class="btn btn-primary"> Créer une analyse</a></h2>
          <p>Liste des analyses</p>
          <p>Patient: {{patient}}</p>
        </div>

        <div class="row">
          {% for analyse in analyses %}
          <div class="col-lg-6">
            <div class="box wow fadeInLeft">
              <div class="icon"> <i class="fa fa-bar-chart"></i> </div>
              <h4 class="title">{{analyse.created_at}} </h4>
              <p class="description"> {{analyse.infected_cells}} </p>
            </div>
          </div>
          {% endfor %}
        </div>

      </div>
    </section><!-- #services -->

  

  </main>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer" style="margin-top: 22% ">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Reveal</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Reveal
        -->
        Designed by <a href="{% static 'https://bootstrapmade.com/' %}" >BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#"  class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}" ></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}" ></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}" ></script>
  <script src="{% static 'lib/easing/easing.min.js' %}" ></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}" ></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}" ></script>
  <script src="{% static 'lib/wow/wow.min.js' %}" ></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}" ></script>
  <script src="{% static 'lib/magnific-popup/magnific-popup.min.js' %}" ></script>
  <script src="{% static 'lib/sticky/sticky.js' %}" ></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}" ></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}" ></script>

</body>
</html>